using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

[CreateAssetMenu(menuName = "WordData", fileName = "WordsList")]
public class WordData : ScriptableObject
{
    public List<string> ThreeLetters = new List<string>
    {
        "ARM",
        "BAG",
        "BAR",
        "BAT",
        "BED",
        "BOX",
        "BOY",
        "BUG",
        "BUS",
        "CAN",
        "CAR",
        "CAT",
        "CUP",
        "DEN",
        "DOG",
        "DOT",
        "DRY",
        "END",
        "FAN",
        "FED",
        "FOG",
        "FOR",
        "FOX",
        "FUN",
        "GOD",
        "GOT",
        "GUM",
        "GYM",
        "HAT",
        "HIP",
        "HOT",
        "INK",
        "JAM",
        "JOB",
        "KEY",
        "KID",
        "LAB",
        "LAW",
        "LEG",
        "LID",
        "LIP",
        "LOT",
        "MAP",
        "MAY",
        "MEN",
        "MOW",
        "MUD",
        "MUG",
        "NAP",
        "NUT",
        "OLD",
        "PAN",
        "PAT",
        "PEN",
        "PIG",
        "PIN",
        "RAG",
        "RAM",
        "RAT",
        "RIB",
        "ROD",
        "RUG",
        "RUN",
        "RUN",
        "SAD",
        "SEE",
        "SEW",
        "SHE",
        "SHY",
        "SIN",
        "SLY",
        "SON",
        "SUN",
        "TAG",
        "TIP",
        "TOE",
        "TOP",
        "TRY",
        "VAN",
        "WET",
        "WIN",
        "WOK",
        "YES",
        "YET"
    };
    public List<string> FourLetters;
    public List<string> FiveLetters;
    
}
